import type {
  AlphaFeedback,
  AlphaFounderNote,
  AlphaPartner,
  AlphaSupportIssue,
  AlphaWeeklyReport,
  OnboardingStep,
  OnboardingStepKey,
} from "@/lib/hq/private-alpha/types";

const STEP_LABELS: Record<OnboardingStepKey, string> = {
  business_profile: "Business Profile",
  locations: "Locations",
  services: "Services",
  employees: "Employees",
  business_hours: "Business Hours",
  branding: "Branding",
  communications: "Communications",
  commerce: "Commerce",
  summer_setup: "Summer Setup",
  chase_setup: "Chase Setup",
  training_complete: "Training Complete",
  go_live: "Go Live",
};

const ALL_STEPS = Object.keys(STEP_LABELS) as OnboardingStepKey[];

function checklist(
  doneKeys: OnboardingStepKey[],
  completedAt?: Partial<Record<OnboardingStepKey, string>>,
): OnboardingStep[] {
  const done = new Set(doneKeys);
  return ALL_STEPS.map((key) => ({
    key,
    label: STEP_LABELS[key],
    done: done.has(key),
    completedAt: done.has(key) ? (completedAt?.[key] ?? "2026-07-01") : undefined,
  }));
}

/** Four Founding Design Partners — Private Alpha cohort. */
export const ALPHA_PARTNERS: AlphaPartner[] = [
  {
    code: "001",
    companyName: "GVM Baby World",
    industry: "Medical imaging / maternity",
    primaryContact: "Ops Lead",
    email: "ops@gvmbabyworld.example",
    phone: "+1 (416) 555-0101",
    status: "active",
    onboarding: checklist(ALL_STEPS, {
      go_live: "2026-06-20",
    }),
    firstLogin: "2026-06-12",
    lastActivity: "2026-07-18",
    weeklyActiveUsers: 6,
    bookingsCreated: 412,
    revenueProcessedLabel: "$18,400",
    supportTicketsOpen: 1,
    featureRequestsOpen: 2,
    openBugs: 1,
    customerSatisfaction: 92,
    healthScore: 88,
    risk: "low",
    nextMeeting: "2026-07-22",
    meetingNotes:
      "Dogfood partner. Strong Summer usage. Wants staff invites before Closed Beta.",
  },
  {
    code: "002",
    companyName: "CarStar",
    industry: "Auto body / collision",
    primaryContact: "Jordan Hale",
    email: "jordan@carstar.example",
    phone: "+1 (905) 555-0142",
    status: "onboarding",
    onboarding: checklist(
      [
        "business_profile",
        "locations",
        "services",
        "employees",
        "business_hours",
        "branding",
        "communications",
      ],
      {
        communications: "2026-07-15",
      },
    ),
    firstLogin: "2026-07-08",
    lastActivity: "2026-07-17",
    weeklyActiveUsers: 3,
    bookingsCreated: 48,
    revenueProcessedLabel: "$2,100",
    supportTicketsOpen: 2,
    featureRequestsOpen: 1,
    openBugs: 0,
    customerSatisfaction: 78,
    healthScore: 71,
    risk: "medium",
    nextMeeting: "2026-07-21",
    meetingNotes:
      "Commerce + Summer still pending. High volume estimate once estimators are trained.",
  },
  {
    code: "003",
    companyName: "Shoppers",
    industry: "Retail pharmacy",
    primaryContact: "Priya Shah",
    email: "priya.shoppers@example",
    phone: "+1 (647) 555-0199",
    status: "onboarding",
    onboarding: checklist(
      [
        "business_profile",
        "locations",
        "services",
        "business_hours",
        "branding",
      ],
      {
        branding: "2026-07-14",
      },
    ),
    firstLogin: "2026-07-10",
    lastActivity: "2026-07-16",
    weeklyActiveUsers: 2,
    bookingsCreated: 19,
    revenueProcessedLabel: "$640",
    supportTicketsOpen: 1,
    featureRequestsOpen: 3,
    openBugs: 1,
    customerSatisfaction: 74,
    healthScore: 64,
    risk: "medium",
    nextMeeting: "2026-07-23",
    meetingNotes:
      "Multi-location interest. Needs clearer pharmacy appointment types before go-live.",
  },
  {
    code: "004",
    companyName: "Darshan's General Construction",
    industry: "Construction / field services",
    primaryContact: "Darshan",
    email: "darshan@dgc.example",
    phone: "+1 (289) 555-0177",
    status: "active",
    onboarding: checklist(
      [
        "business_profile",
        "locations",
        "services",
        "employees",
        "business_hours",
        "branding",
        "communications",
        "commerce",
        "summer_setup",
        "training_complete",
        "go_live",
      ],
      {
        go_live: "2026-07-05",
        chase_setup: undefined,
      },
    ),
    firstLogin: "2026-06-28",
    lastActivity: "2026-07-18",
    weeklyActiveUsers: 4,
    bookingsCreated: 87,
    revenueProcessedLabel: "$9,250",
    supportTicketsOpen: 0,
    featureRequestsOpen: 1,
    openBugs: 0,
    customerSatisfaction: 90,
    healthScore: 84,
    risk: "low",
    nextMeeting: "2026-07-24",
    meetingNotes:
      "Founder dogfood. Chase partially configured — finish before weekly review.",
  },
];

export const ALPHA_FEEDBACK: AlphaFeedback[] = [
  {
    id: "fb-1",
    partnerCode: "001",
    partnerName: "GVM Baby World",
    title: "Staff invitations + role permissions",
    status: "planned",
    roadmapItemId: "r6",
    roadmapLabel: "Staff invites + RBAC",
    createdAt: "2026-07-02",
    updatedAt: "2026-07-16",
  },
  {
    id: "fb-2",
    partnerCode: "001",
    partnerName: "GVM Baby World",
    title: "Ultrasound-specific intake forms",
    status: "under_review",
    roadmapItemId: null,
    roadmapLabel: null,
    createdAt: "2026-07-11",
    updatedAt: "2026-07-17",
  },
  {
    id: "fb-3",
    partnerCode: "002",
    partnerName: "CarStar",
    title: "Estimator multi-vehicle booking flow",
    status: "new",
    roadmapItemId: null,
    roadmapLabel: null,
    createdAt: "2026-07-15",
    updatedAt: "2026-07-15",
  },
  {
    id: "fb-4",
    partnerCode: "003",
    partnerName: "Shoppers",
    title: "Pharmacy consult appointment types",
    status: "in_progress",
    roadmapItemId: "r4",
    roadmapLabel: "Persist design-partner applications",
    createdAt: "2026-07-12",
    updatedAt: "2026-07-18",
  },
  {
    id: "fb-5",
    partnerCode: "003",
    partnerName: "Shoppers",
    title: "SMS quiet hours for retail hours",
    status: "planned",
    roadmapItemId: null,
    roadmapLabel: "Communications platform",
    createdAt: "2026-07-13",
    updatedAt: "2026-07-16",
  },
  {
    id: "fb-6",
    partnerCode: "003",
    partnerName: "Shoppers",
    title: "Franchise roll-up reporting",
    status: "rejected",
    roadmapItemId: null,
    roadmapLabel: null,
    createdAt: "2026-07-09",
    updatedAt: "2026-07-14",
  },
  {
    id: "fb-7",
    partnerCode: "004",
    partnerName: "Darshan's General Construction",
    title: "Job-site visit scheduling from Chase",
    status: "completed",
    roadmapItemId: "r3",
    roadmapLabel: "Chasum HQ Founder OS",
    createdAt: "2026-07-01",
    updatedAt: "2026-07-10",
  },
];

export const ALPHA_SUPPORT: AlphaSupportIssue[] = [
  {
    id: "sup-1",
    partnerCode: "001",
    partnerName: "GVM Baby World",
    title: "Calendar conflict toast when two staff book same room",
    severity: "medium",
    status: "assigned",
    assignedTo: "Founder",
    reportedAt: "2026-07-17",
    resolvedAt: null,
  },
  {
    id: "sup-2",
    partnerCode: "002",
    partnerName: "CarStar",
    title: "Deposit collection stub in Booking Sheet",
    severity: "high",
    status: "reported",
    assignedTo: null,
    reportedAt: "2026-07-16",
    resolvedAt: null,
  },
  {
    id: "sup-3",
    partnerCode: "002",
    partnerName: "CarStar",
    title: "Need help importing estimator CSV",
    severity: "low",
    status: "assigned",
    assignedTo: "Founder",
    reportedAt: "2026-07-14",
    resolvedAt: null,
  },
  {
    id: "sup-4",
    partnerCode: "003",
    partnerName: "Shoppers",
    title: "Branding logo crop on receipt email",
    severity: "low",
    status: "reported",
    assignedTo: null,
    reportedAt: "2026-07-15",
    resolvedAt: null,
  },
  {
    id: "sup-5",
    partnerCode: "004",
    partnerName: "Darshan's General Construction",
    title: "Chase report empty for first week",
    severity: "medium",
    status: "resolved",
    assignedTo: "Founder",
    reportedAt: "2026-07-06",
    resolvedAt: "2026-07-08",
  },
];

export const ALPHA_WEEKLY_REPORT: AlphaWeeklyReport = {
  weekOf: "2026-07-14",
  summary:
    "Four founding partners live in Private Alpha. GVM and DGC healthy; CarStar and Shoppers still finishing onboarding. Focus next week: Commerce for CarStar, appointment taxonomy for Shoppers, Chase complete for DGC.",
  companies: [
    {
      partnerCode: "001",
      companyName: "GVM Baby World",
      wins: [
        "412 lifetime bookings — strongest usage",
        "Summer handling intake questions reliably",
      ],
      problems: ["One medium calendar conflict ticket"],
      requestedFeatures: ["Staff invites", "Ultrasound intake forms"],
      health: 88,
      usage: "6 WAU · high booking velocity",
    },
    {
      partnerCode: "002",
      companyName: "CarStar",
      wins: ["Profile + services configured", "Team training scheduled"],
      problems: ["Commerce not live", "Deposit stub blocking trust"],
      requestedFeatures: ["Estimator multi-vehicle flow"],
      health: 71,
      usage: "3 WAU · early bookings",
    },
    {
      partnerCode: "003",
      companyName: "Shoppers",
      wins: ["Branding uploaded", "Locations sketched"],
      problems: ["Employees + Summer incomplete", "Slow last activity"],
      requestedFeatures: [
        "Pharmacy consult types",
        "SMS quiet hours",
        "Franchise roll-up (rejected for alpha)",
      ],
      health: 64,
      usage: "2 WAU · light bookings",
    },
    {
      partnerCode: "004",
      companyName: "Darshan's General Construction",
      wins: ["Go-live complete", "Solid CSAT"],
      problems: ["Chase setup unfinished"],
      requestedFeatures: ["Job-site visits from Chase (shipped)"],
      health: 84,
      usage: "4 WAU · steady field bookings",
    },
  ],
};

export const ALPHA_FOUNDER_NOTES: AlphaFounderNote[] = [
  {
    id: "note-1",
    partnerCode: "001",
    title: "GVM — expand carefully",
    body: "Best reference for Private Alpha case study. Do not promise multi-staff RBAC dates until Stripe Billing honesty is fixed.",
    createdAt: "2026-07-10",
    updatedAt: "2026-07-18",
  },
  {
    id: "note-2",
    partnerCode: "002",
    title: "CarStar — unblock Commerce",
    body: "They will churn emotionally if deposits stay stubbed. Prioritize Stripe Elements path before next meeting.",
    createdAt: "2026-07-16",
    updatedAt: "2026-07-17",
  },
  {
    id: "note-3",
    partnerCode: "003",
    title: "Shoppers — scope discipline",
    body: "Reject franchise roll-up for alpha. Keep them on single-location success story first.",
    createdAt: "2026-07-14",
    updatedAt: "2026-07-14",
  },
  {
    id: "note-4",
    partnerCode: null,
    title: "Cohort operating rhythm",
    body: "Weekly founder review every Monday. One meeting per partner max. Log support same day. Feedback status must move within 7 days.",
    createdAt: "2026-07-07",
    updatedAt: "2026-07-18",
  },
];
