-- Issue #72. CODE ONLY: application to a governed environment requires a separate gate.
-- Timestamp generated by `supabase migration new`; no historical migration changed.
-- Prerequisites: 007/008/011/014/023/032/033/039. No dependency on 034-036.
-- Run transactionally. Unexpected creation policies fail closed for reconciliation.
set lock_timeout = '5s';

do $$
begin
  if exists (select 1 from pg_policy where polrelid = 'public.businesses'::regclass
      and polcmd in ('a', '*') and polname <> 'Owners manage their businesses') then
    raise exception 'Unexpected businesses creation policy; review before applying';
  end if;
  if to_regclass('public.businesses_one_per_owner_idx') is null then
    raise exception 'One-owner uniqueness prerequisite missing';
  end if;
end $$;

drop policy "Owners manage their businesses" on public.businesses;
create policy "Owners read their businesses" on public.businesses for select to authenticated
  using (owner_id = auth.uid() or public.is_business_owner(id));
create policy "Owners update their businesses" on public.businesses for update to authenticated
  using (owner_id = auth.uid() or public.is_business_owner(id))
  with check (owner_id = auth.uid() or public.is_business_owner(id));
create policy "Owners delete their businesses" on public.businesses for delete to authenticated
  using (owner_id = auth.uid() or public.is_business_owner(id));
create policy "No client business creation" on public.businesses as restrictive for insert to anon, authenticated
  with check (false);
revoke insert on public.businesses from public, anon, authenticated;
-- Preserve existing public booking SELECT and legitimate owner/member UPDATE.

-- Identity cannot be reassigned through the ordinary profile UPDATE path.
create function public.guard_business_identity_update() returns trigger
language plpgsql set search_path = pg_catalog, public, pg_temp as $$
begin
  if current_user in ('anon', 'authenticated') and
     (new.id is distinct from old.id or new.owner_id is distinct from old.owner_id) then
    raise exception 'Business identity transfer requires governed review' using errcode = '42501';
  end if;
  return new;
end $$;
revoke all on function public.guard_business_identity_update() from public, anon, authenticated;
create trigger businesses_guard_identity_update before update on public.businesses
for each row execute function public.guard_business_identity_update();

-- Retain the legacy signature, but remove ALL creation/seed behavior, even for
-- privileged callers. Old authenticated clients can only resolve their tenant.
create or replace function public.ensure_business_for_owner(p_name text, p_preferred_slug text)
returns public.businesses language sql stable security definer
set search_path = pg_catalog, public, pg_temp as $$
  select b from public.businesses b
  where b.owner_id = auth.uid() or exists (
    select 1 from public.business_members m
    where m.business_id = b.id and m.user_id = auth.uid() and m.role in ('owner', 'admin')
  )
  order by exists (select 1 from public.business_members m
    where m.business_id = b.id and m.user_id = auth.uid()) desc,
    b.private_alpha_enabled desc, b.created_at, b.id
  limit 1;
$$;
revoke all on function public.ensure_business_for_owner(text, text) from public, anon;
grant execute on function public.ensure_business_for_owner(text, text) to authenticated;

create table public.tenant_identity_decisions (
  id uuid primary key default gen_random_uuid(),
  actor_user_id uuid not null references auth.users(id),
  decision text not null check (decision in ('create_new','join_existing','ambiguous_stop','private_alpha_override')),
  candidate_business_id uuid references public.businesses(id),
  resulting_business_id uuid references public.businesses(id),
  reason_code text not null check (reason_code in ('no_blocking_match','access_requested','identity_overlap','reviewed_separate_business')),
  signal_kinds text[] not null default '{}' check (signal_kinds <@ array[
    'phone','email','website','name_location','brand_location','requested_slug']::text[]),
  reviewed_by uuid references public.platform_admins(user_id),
  created_at timestamptz not null default now(),
  check (
    (decision = 'create_new' and reason_code = 'no_blocking_match' and resulting_business_id is not null and candidate_business_id is null and reviewed_by is null and cardinality(signal_kinds) = 0)
    or (decision = 'join_existing' and reason_code = 'access_requested' and resulting_business_id is null and candidate_business_id is null and reviewed_by is null and cardinality(signal_kinds) = 0)
    or (decision = 'ambiguous_stop' and reason_code = 'identity_overlap' and candidate_business_id is not null and resulting_business_id is null and reviewed_by is null and cardinality(signal_kinds) > 0)
    or (decision = 'private_alpha_override' and reason_code = 'reviewed_separate_business' and reviewed_by is not null and candidate_business_id is not null and resulting_business_id is not null)
  )
);
alter table public.tenant_identity_decisions enable row level security;
-- No client policies, including no ordinary tenant-owner visibility of candidates.
revoke all on public.tenant_identity_decisions from public, anon, authenticated, service_role;
grant select, insert on public.tenant_identity_decisions to service_role;
create index tenant_identity_decisions_actor_created_idx on public.tenant_identity_decisions(actor_user_id, created_at);

-- Pure normalization only, never an identity proof. Not a public discovery API.
create function public.tenant_identity_key(p_value text, p_kind text) returns text
language sql immutable set search_path = pg_catalog as $$
  select case p_kind
    when 'email' then nullif(lower(btrim(p_value)), '')
    when 'phone' then nullif(regexp_replace(regexp_replace(p_value, '[^0-9]', '', 'g'), '^1([0-9]{10})$', '\1'), '')
    when 'website' then nullif(regexp_replace(split_part(split_part(split_part(regexp_replace(lower(btrim(p_value)), '^https?://', ''), '/', 1), '?', 1), '#', 1), '^www\.|:[0-9]+$|\.$', '', 'g'), '')
    else nullif(regexp_replace(lower(p_value), '[^[:alnum:]]', '', 'g'), '')
  end;
$$;
revoke all on function public.tenant_identity_key(text,text) from public, anon, authenticated;

-- Sole create-capable entry: service-role only, called by an authenticated server
-- action. Preflight is inside the writer, not a reusable browser approval token.
create function public.decide_business_identity(
  p_actor_user_id uuid, p_intent text, p_name text, p_legal_name text,
  p_email text, p_phone text, p_website text, p_city text, p_region text,
  p_country text, p_requested_slug text
) returns jsonb language plpgsql security definer
set search_path = pg_catalog, public, pg_temp
set lock_timeout = '5s'
as $$
declare
  v_user auth.users;
  v_business public.businesses;
  v_match record;
  v_slug text;
  v_base text;
  v_location uuid;
  v_attempt integer := 0;
  v_name text := public.tenant_identity_key(p_name, 'name');
  v_legal text := public.tenant_identity_key(p_legal_name, 'name');
  v_phone text := public.tenant_identity_key(p_phone, 'phone');
  v_email text := public.tenant_identity_key(p_email, 'email');
  v_host text := public.tenant_identity_key(p_website, 'website');
  v_city text := public.tenant_identity_key(p_city, 'name');
  v_region text := public.tenant_identity_key(p_region, 'name');
begin
  if p_intent is null or p_intent not in ('create_new', 'join_existing') then
    raise exception 'Invalid identity intent' using errcode = '22023';
  end if;
  select * into v_user from auth.users where id = p_actor_user_id for update;
  if not found or v_user.email_confirmed_at is null or v_user.is_anonymous is true
     or v_user.banned_until > now() then
    raise exception 'Verified active account required' using errcode = '42501';
  end if;
  -- Short serialized gate also prevents cross-account same-identity creation.
  -- Table locks cover concurrent profile/location/member writes during preflight.
  -- No network work occurs while held. Bounded lock timeout fails closed.
  lock table public.businesses, public.business_members, public.locations,
    public.business_slug_aliases in share row exclusive mode;
  if exists (select 1 from public.businesses where owner_id = p_actor_user_id)
     or exists (select 1 from public.business_members where user_id = p_actor_user_id) then
    return jsonb_build_object('status', 'existing');
  end if;
  if coalesce(v_user.raw_app_meta_data, '{}'::jsonb) ? 'chasum_operator' then
    raise exception 'Existing business access must be resolved' using errcode = '42501';
  end if;
  if (select count(*) from public.tenant_identity_decisions
      where actor_user_id = p_actor_user_id and created_at > now() - interval '1 day') >= 10 then
    return jsonb_build_object('status', 'review_required');
  end if;
  if p_intent = 'join_existing' then
    insert into public.tenant_identity_decisions(actor_user_id, decision, reason_code)
    values (p_actor_user_id, 'join_existing', 'access_requested');
    return jsonb_build_object('status', 'join_existing');
  end if;
  if v_name is null or length(btrim(p_name)) not between 2 and 120
     or length(coalesce(p_legal_name,'')) > 120
     or v_email is null or length(v_email) > 254 or v_email !~ '^[^[:space:]@]+@[^[:space:]@]+\.[^[:space:]@]+$'
     or v_phone is null or length(v_phone) not between 7 and 15 or length(p_phone) > 40
     or v_city is null or length(p_city) > 100 or v_region is null or length(p_region) > 100
     or p_country is null or p_country !~ '^[A-Za-z]{2}$'
     or (p_website is not null and (length(p_website) > 255 or v_host is null or v_host !~ '^[a-z0-9.-]+\.[a-z]{2,}$'))
     or (p_requested_slug is not null and (length(p_requested_slug) not between 3 and 48 or p_requested_slug !~ '^[a-z0-9]+(-[a-z0-9]+)*$')) then
    raise exception 'Invalid business identity' using errcode = '22023';
  end if;

  -- Select one deterministic candidate for internal audit. NEVER return it to UI.
  with evidence as (
    select b.id, array_remove(array[
      case when public.tenant_identity_key(b.phone,'phone') = v_phone or exists (
        select 1 from public.locations l where l.business_id=b.id and public.tenant_identity_key(l.phone,'phone')=v_phone
      ) then 'phone' end,
      case when public.tenant_identity_key(b.email,'email') = v_email then 'email' end,
      case when v_host is not null and (
        public.tenant_identity_key(b.website,'website') = v_host
        or v_host like '%.' || public.tenant_identity_key(b.website,'website')
        or public.tenant_identity_key(b.website,'website') like '%.' || v_host
      ) then 'website' end,
      case when (public.tenant_identity_key(b.name,'name') in (v_name,v_legal)
                 or public.tenant_identity_key(b.legal_name,'name') in (v_name,v_legal))
        and ((public.tenant_identity_key(b.city,'name')=v_city and public.tenant_identity_key(b.state,'name')=v_region)
          or exists (select 1 from public.locations l where l.business_id=b.id
            and public.tenant_identity_key(l.city,'name')=v_city and public.tenant_identity_key(l.state,'name')=v_region))
        then 'name_location' end,
      case when length(v_name)>=4 and length(public.tenant_identity_key(b.name,'name'))>=4
        and (position(public.tenant_identity_key(b.name,'name') in v_name)>0 or position(v_name in public.tenant_identity_key(b.name,'name'))>0)
        and ((public.tenant_identity_key(b.city,'name')=v_city and public.tenant_identity_key(b.state,'name')=v_region)
          or exists (select 1 from public.locations l where l.business_id=b.id
            and public.tenant_identity_key(l.city,'name')=v_city and public.tenant_identity_key(l.state,'name')=v_region))
        then 'brand_location' end,
      case when p_requested_slug is not null and (b.slug=p_requested_slug or exists (
        select 1 from public.business_slug_aliases a where a.business_id=b.id and a.slug=p_requested_slug
      )) then 'requested_slug' end
    ], null)::text[] signals from public.businesses b
  ) select * into v_match from evidence where cardinality(signals)>0 order by id limit 1;
  if found then
    insert into public.tenant_identity_decisions(actor_user_id, decision, candidate_business_id, reason_code, signal_kinds)
    values (p_actor_user_id, 'ambiguous_stop', v_match.id, 'identity_overlap', v_match.signals);
    return jsonb_build_object('status','ambiguous');
  end if;

  v_base := coalesce(p_requested_slug, nullif(left(trim(both '-' from regexp_replace(lower(p_name),'[^a-z0-9]+','-','g')),48),''), 'business');
  loop
    v_slug := case when v_attempt=0 then v_base else v_base || '-' || v_attempt::text end;
    exit when not exists (select 1 from public.businesses where slug=v_slug)
      and not exists (select 1 from public.business_slug_aliases where slug=v_slug);
    v_attempt := v_attempt+1;
    if v_attempt>100 then raise exception 'Booking link allocation needs review'; end if;
  end loop;
  insert into public.businesses(owner_id,name,legal_name,slug,email,phone,website,city,state,country,appointment_interval_minutes)
  values (p_actor_user_id,btrim(p_name),nullif(btrim(p_legal_name),''),v_slug,v_email,btrim(p_phone),p_website,btrim(p_city),btrim(p_region),upper(p_country),15)
  returning * into v_business;
  insert into public.business_hours(business_id,day_of_week,is_open,open_time,close_time)
    select v_business.id, day, day between 1 and 5, '09:00'::time, '17:00'::time from generate_series(0,6) day;
  v_location := public.create_default_location(v_business.id, v_business.name || ' — Main');
  update public.locations set city=btrim(p_city), state=btrim(p_region), phone=btrim(p_phone) where id=v_location;
  insert into public.tenant_identity_decisions(actor_user_id,decision,resulting_business_id,reason_code)
    values (p_actor_user_id,'create_new',v_business.id,'no_blocking_match');
  return jsonb_build_object('status','created','business',to_jsonb(v_business));
end $$;
revoke all on function public.decide_business_identity(uuid,text,text,text,text,text,text,text,text,text,text) from public, anon, authenticated;
grant execute on function public.decide_business_identity(uuid,text,text,text,text,text,text,text,text,text,text) to service_role;
-- No override input/function exists. A future Platform Admin override must be
-- independently authorized and bind its review to the exact identity before create.
notify pgrst, 'reload schema';
reset lock_timeout;
